name: LONE Build and Push API & Web 

permissions:
      id-token: write
      contents: read 

on:
  workflow_dispatch:
    inputs:
      create_lone_web:
        description: 'LONE Web'
        required: false 
        type: boolean
      create_lone_api:
        description: 'LONE API'
        required: false 
        type: boolean
      lone-web-version-tag:
        description: 'LONE Web version Tag'     
        required: true
        default: 'latest'
      lone-api-version-tag:
        description: 'LONE API version Tag'     
        required: true
        default: 'latest'

jobs:
  Docker:
    name: Build and Push LONE Docker Images
    runs-on: ubuntu-latest
    
    environment: inter-site 
    env:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}            

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: eu-west-2
        role-session-name: LONE_GitAction        

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push the API to ECR
      if: ${{ github.event.inputs.create_lone_api == 'true' }}
      id: build-push-API
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: lone-api
        IMAGE_TAG: ${{ github.event.inputs.lone-api-version-tag }}
      run: |
        # Build the API docker container and push it to ECR 
        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} -f Dockerfile-api .
        echo "Pushing image to ECR..."
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        echo "::set-output name=image::${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
    - name: Build, tag, and push the Web to ECR
      if: ${{ github.event.inputs.create_lone_web == 'true' }}
      id: build-push-Web
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: lone-web
        IMAGE_TAG: ${{ github.event.inputs.lone-web-version-tag }}
      run: |
        # Build the Web docker container and push it to ECR 
        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} -f Dockerfile-web .
        echo "Pushing image to ECR..."
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        echo "::set-output name=image::${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"